# version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
  frontend:
    image: node:18.18
    # ports:
    #   - "5173:5173"
    command: sh entrypoint.sh
    working_dir: /mycry
    volumes:
      - ./mycry/:/mycry
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./mycry/dist:/var/www/mycry
    depends_on:
      - backend
  redis:
    image: redis
    ports:
      - "6379:6379"