# Generated by Django 4.2.9 on 2024-10-05 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶基本資料',
                'verbose_name_plural': '用戶基本資料',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '註冊Token',
                'verbose_name_plural': '註冊Token',
            },
        ),
        migrations.CreateModel(
            name='UserWithdrawStakeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transHash', models.CharField(blank=True, max_length=128, null=True)),
                ('transTime', models.DateTimeField(blank=True, null=True)),
                ('withdrawAmount', models.CharField(blank=True, max_length=10, null=True)),
                ('stake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawStakeHistory', to=settings.AUTH_USER_MODEL, to_field='userID')),
            ],
            options={
                'verbose_name': '質押提領紀錄',
                'verbose_name_plural': '質押提領紀錄',
            },
        ),
        migrations.CreateModel(
            name='UserSetStakeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transHash', models.CharField(blank=True, max_length=128, null=True)),
                ('transTime', models.DateTimeField(blank=True, null=True)),
                ('stakeAmount', models.CharField(blank=True, max_length=10, null=True)),
                ('stake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setStakeHistory', to=settings.AUTH_USER_MODEL, to_field='userID')),
            ],
            options={
                'verbose_name': '質押紀錄',
                'verbose_name_plural': '質押紀錄',
            },
        ),
        migrations.CreateModel(
            name='UserPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transHash', models.CharField(blank=True, max_length=128, null=True)),
                ('transTime', models.DateTimeField(blank=True, null=True)),
                ('payToken', models.CharField(blank=True, max_length=10, null=True)),
                ('payAmount', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseHistory', to=settings.AUTH_USER_MODEL, to_field='userID')),
            ],
            options={
                'verbose_name': '購買Token紀錄',
                'verbose_name_plural': '購買Token紀錄',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethPrivateKey', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ethPublicKey', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ethAddress', models.CharField(blank=True, max_length=128, null=True)),
                ('ethBalance', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=30, null=True)),
                ('usdtBalance', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=30, null=True)),
                ('tokenBalance', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=30, null=True)),
                ('staked', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, to_field='userID')),
            ],
            options={
                'verbose_name': '用戶地址',
                'verbose_name_plural': '用戶地址',
            },
        ),
    ]
